# -*- coding: utf-8 -*-
"""EduLink_Matching_Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZmB3ERWsBlAdJaZ3qQIXCdJ9DieCk1Kf

# EduLink Matching Demo – BM25/TF‑IDF, Embeddings, Knowledge Graph, Hybrid + Re‑Ranking

This notebook shows **four methodologies** to match student projects to professors using your KMUTT datasets:

1) **Keyword / Tag Matching (TF‑IDF)** – fast lexical baseline  
2) **Embedding Similarity (Vector Search)** – semantic search with sentence-transformers  
3) **Knowledge Graph Matching** – topic overlap / neighborhood-style scoring  
4) **Hybrid (TF‑IDF + KG) + Re‑Ranking** – union recall then (optionally) re-rank via a cross-encoder

It also includes a light **evaluation** (Recall@K) by treating each paper abstract as a "student project" and checking whether the paper's author (professor) appears in the top‑K.

## 0. Setup
"""

!pip -q install scikit-learn pandas numpy tqdm
# Optional (for embeddings & cross-encoder reranker):
!pip -q install sentence-transformers torch

import os, ast, math, random, json
from collections import defaultdict, Counter
import numpy as np
import pandas as pd
from tqdm import tqdm

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

# Paths – adjust as needed
PROF_PATH = "/content/kmutt_professors.csv"
PAPER_PATH = "/content/kmutt_papers.csv"

"""## 1. Load & Preprocess Data"""

def read_csv_best(path):
    try:
        return pd.read_csv(path)
    except UnicodeDecodeError:
        return pd.read_csv(path, encoding="utf-8-sig")

prof_raw = read_csv_best(PROF_PATH)
paper_raw = read_csv_best(PAPER_PATH)

print("Professors rows:", len(prof_raw), "| columns:", list(prof_raw.columns))
print("Papers rows:", len(paper_raw), "| columns:", list(paper_raw.columns))

def parse_topics(x):
    if pd.isna(x):
        return []
    if isinstance(x, list):
        return x
    try:
        v = ast.literal_eval(x)
        if isinstance(v, list):
            return [str(s).strip() for s in v]
        return [str(v)]
    except Exception:

        return [t.strip() for t in str(x).split(",") if t.strip()]

for df in (prof_raw, paper_raw):
    df["topics_list"] = df["topics"].apply(parse_topics)
    # Base text blob: work_title + abstract + topics
    df["base_text"] = (
        df["work_title"].fillna("") + " " +
        df["abstract_excerpt"].fillna("") + " " +
        df["topics_list"].apply(lambda xs: " ".join(xs))
    ).str.lower()

# Aggregate per professor (merge multiple papers into one profile)
def build_prof_profiles(df):
    profs = []
    for name, g in df.groupby(["professor_name", "author_id"]):
        texts = g["base_text"].tolist()
        titles = g["work_title"].dropna().tolist()
        topics = [t for xs in g["topics_list"].tolist() for t in xs]
        profs.append({
            "professor_name": name[0],
            "author_id": name[1],
            "n_papers": len(g),
            "titles_recent": titles[:5],
            "topics_set": sorted(list(set(topics))),
            "profile_text": " ".join(texts)
        })
    return pd.DataFrame(profs)

prof_df = build_prof_profiles(prof_raw)
print("Unique professors:", len(prof_df))
prof_df.head(3)

"""## 2. Create Synthetic Student Queries for Evaluation"""

#use each paper as a "student project" query.
# Ground truth: the professor who authored that paper.

queries = paper_raw[["professor_name","author_id","work_title","abstract_excerpt","topics_list"]].copy()
queries["query_text"] = (
    queries["work_title"].fillna("") + " " +
    queries["abstract_excerpt"].fillna("") + " " +
    queries["topics_list"].apply(lambda xs: " ".join(xs))
).str.lower()

print("Queries:", len(queries))
queries.head(3)

"""## 3. Method 1 – TF‑IDF / Keyword Matching

Build TF-IDF index on professor profiles
"""

tfidf = TfidfVectorizer(max_features=50000, ngram_range=(1,2), stop_words='english')
X_prof = tfidf.fit_transform(prof_df["profile_text"])

def tfidf_search(query_text, topk=10):
    qv = tfidf.transform([query_text])
    sims = cosine_similarity(qv, X_prof).ravel()
    top_idx = np.argsort(-sims)[:topk]
    results = prof_df.iloc[top_idx][["professor_name","author_id","topics_set","n_papers"]].copy()
    results["score"] = sims[top_idx]
    return results


sample_q = queries.iloc[0]["query_text"]
tfidf_search(sample_q, topk=5)

"""
## 4. Method 2 – Embedding Similarity (Sentence-Transformers)

- `intfloat/e5-large-v2` (English) or `intfloat/multilingual-e5-large` (Thai/EN)
- `sentence-transformers/all-mpnet-base-v2` (English)
- Academic-specific: `allenai/specter2`
"""

USE_EMBEDDINGS = True

if USE_EMBEDDINGS:
    try:
        from sentence_transformers import SentenceTransformer, util
        embed_model_name = "intfloat/multilingual-e5-large"
        emb_model = SentenceTransformer(embed_model_name)
        prof_emb = emb_model.encode(prof_df["profile_text"].tolist(), batch_size=64, show_progress_bar=True, normalize_embeddings=True)
        prof_emb = np.array(prof_emb)
    except Exception as e:
        print("Embedding model setup failed:", e)
        USE_EMBEDDINGS = False
        prof_emb = None

def embed_search(query_text, topk=10):
    if not USE_EMBEDDINGS or emb_model is None:
        raise RuntimeError("Embedding model not available. Set USE_EMBEDDINGS=True in Colab with internet.")
    qv = emb_model.encode([query_text], normalize_embeddings=True)
    sims = (qv @ prof_emb.T).ravel()   # cosine since normalized
    top_idx = np.argsort(-sims)[:topk]
    results = prof_df.iloc[top_idx][["professor_name","author_id","topics_set","n_papers"]].copy()
    results["score"] = sims[top_idx]
    return results

# if embeddings loaded)
if USE_EMBEDDINGS:
    embed_search(sample_q, topk=5)

"""## 5. Method 3 – Knowledge Graph Matching (Topic Overlap)"""

# Build lookup: author_id -> set(topics)
prof_topics = {row.author_id: set(row.topics_set) for _, row in prof_df.iterrows()}

def topic_overlap_score(q_topics, p_topics):
    if not q_topics or not p_topics:
        return 0.0
    inter = len(set(q_topics) & set(p_topics))
    uni = len(set(q_topics) | set(p_topics))
    return inter / uni  # Jaccard

def kg_search(query_topics, topk=10):
    scores = []
    for i, row in prof_df.iterrows():
        s = topic_overlap_score(query_topics, row.topics_set)
        scores.append(s)
    scores = np.array(scores)
    top_idx = np.argsort(-scores)[:topk]
    results = prof_df.iloc[top_idx][["professor_name","author_id","topics_set","n_papers"]].copy()
    results["score"] = scores[top_idx]
    return results


sample_topics = queries.iloc[0]["topics_list"]
kg_search(sample_topics, topk=5)

"""## 6. Method 4 – Hybrid Recall (TF‑IDF ∪ KG) + Optional Re‑Ranking"""

# Recall phase: take union of TF-IDF topN and KG topN -> candidate pool
# Re-rank phase: either weighted sum or cross-encoder reranker (if available)

def hybrid_candidates(query_text, query_topics, tfidf_k=100, kg_k=100):
    tfidf_res = tfidf_search(query_text, topk=tfidf_k)
    kg_res = kg_search(query_topics, topk=kg_k)
    cand_ids = set(tfidf_res["author_id"]).union(set(kg_res["author_id"]))
    cand_df = prof_df[prof_df["author_id"].isin(cand_ids)].copy()
    # Pre-compute base scores for weighted fusion
    tfidf_full = tfidf.transform([query_text]).toarray().ravel()
    prof_mat = X_prof.toarray()
    tfidf_scores = cosine_similarity([tfidf_full], prof_mat).ravel()
    topic_scores = np.array([topic_overlap_score(query_topics, row.topics_set) for _, row in prof_df.iterrows()])
    cand_df["tfidf_score"] = tfidf_scores[prof_df["author_id"].isin(cand_ids)]
    cand_df["kg_score"] = topic_scores[prof_df["author_id"].isin(cand_ids)]
    return cand_df

# cross-encoder reranker
USE_RERANKER = False  # if  sentence-transformers

if USE_RERANKER:
    try:
        from sentence_transformers.cross_encoder import CrossEncoder
        rerank_model_name = "BAAI/bge-reranker-large"
        reranker = CrossEncoder(rerank_model_name)
    except Exception as e:
        print("Reranker setup failed:", e)
        USE_RERANKER = False

def hybrid_search(query_text, query_topics, topk=10, w_tfidf=0.6, w_kg=0.4):
    cands = hybrid_candidates(query_text, query_topics, tfidf_k=150, kg_k=150)

    if USE_RERANKER:
        # Build pairs: (query_text, professor_profile_text)
        pairs = [(query_text, txt) for txt in cands["profile_text"].tolist()]
        scores = reranker.predict(pairs)  # higher is better
        cands["rerank_score"] = scores
        cands["final_score"] = cands["rerank_score"]
    else:
        # Weighted late-fusion
        cands["final_score"] = w_tfidf * cands["tfidf_score"].fillna(0) + w_kg * cands["kg_score"].fillna(0)

    cands = cands.sort_values("final_score", ascending=False).head(topk)
    return cands[["professor_name","author_id","topics_set","n_papers","final_score"]]

"""## 7. Unified Query Helper"""

def query_professors(project_title:str, project_desc:str, project_topics:list, method:str="tfidf", topk:int=10):
    query_text = f"{project_title} {project_desc} " + " ".join(project_topics or [])
    method = method.lower()
    if method == "tfidf":
        return tfidf_search(query_text, topk=topk)
    elif method == "embed":
        return embed_search(query_text, topk=topk)
    elif method == "kg":
        return kg_search(project_topics or [], topk=topk)
    elif method == "hybrid":
        return hybrid_search(query_text, project_topics or [], topk=topk)
    else:
        raise ValueError("method must be one of: tfidf | embed | kg | hybrid")

"""#Use model example"""

project_title_input = input("Enter project title: ")
project_desc_input = input("Enter project description: ")
project_topics_input = input("Enter project topics (comma-separated): ")
project_topics_list = [topic.strip() for topic in project_topics_input.split(',') if topic.strip()]

demo_user_input = query_professors(
    project_title=project_title_input,
    project_desc=project_desc_input,
    project_topics=project_topics_list,
    method="tfidf",
    topk=5
)
display(demo_user_input)
demo_user_input = query_professors(
    project_title=project_title_input,
    project_desc=project_desc_input,
    project_topics=project_topics_list,
    method="embed",
    topk=5
)
display(demo_user_input)
demo_user_input = query_professors(
    project_title=project_title_input,
    project_desc=project_desc_input,
    project_topics=project_topics_list,
    method="kg",
    topk=5
)
display(demo_user_input)
demo_user_input = query_professors(
    project_title=project_title_input,
    project_desc=project_desc_input,
    project_topics=project_topics_list,
    method="hybrid",
    topk=5
)
display(demo_user_input)

"""## 8. Evaluation (Automatic, Weak-Label)"""

# treat each paper as a query; the correct professor is the paper's author.
# Metric: Recall@K (K in {1,3,5,10}). evaluate for TF-IDF, KG, Hybrid.
# Embeddings + Reranker can be enabled by toggling flags

def recall_at_k(ranked_author_ids, gold_author_id, K):
    return 1.0 if gold_author_id in ranked_author_ids[:K] else 0.0

def evaluate(method="tfidf", n_samples=200, Ks=(1,3,5,10)):
    sample = queries.sample(min(n_samples, len(queries)), random_state=SEED)
    recalls = {K: [] for K in Ks}

    for _, row in tqdm(sample.iterrows(), total=len(sample)):
        qtext = row["query_text"]
        qtopics = row["topics_list"]
        gold = row["author_id"]
        if method == "tfidf":
            res = tfidf_search(qtext, topk=max(Ks))
        elif method == "kg":
            res = kg_search(qtopics or [], topk=max(Ks))
        elif method == "hybrid":
            res = hybrid_search(qtext, qtopics or [], topk=max(Ks))
        elif method == "embed":
            if not USE_EMBEDDINGS:
                continue
            res = embed_search(qtext, topk=max(Ks))
        else:
            raise ValueError(method)

        ranked = res["author_id"].tolist()
        for K in Ks:
            recalls[K].append(recall_at_k(ranked, gold, K))

    out = {f"Recall@{K}": float(np.mean(recalls[K])) if recalls[K] else None for K in Ks}
    return out

print("Evaluating... this may take a minute.")
# eval_tfidf = evaluate("tfidf", n_samples=200)
eval_kg = evaluate("kg", n_samples=200)
eval_hybrid = evaluate("hybrid", n_samples=200)
# Optionally, enable embeddings first to run:
# eval_embed = evaluate("embed", n_samples=200)

# print("\nTF-IDF:", eval_tfidf)
# print("\nEmbedding:", eval_embed)

print("KG    :", eval_kg)
print("Hybrid:", eval_hybrid)

"""### 9. Saving Models to `.pkl` files"""

import pickle

# Save TF-IDF Vectorizer
with open('tfidf_vectorizer.pkl', 'wb') as f:
    pickle.dump(tfidf, f)
print("TF-IDF Vectorizer saved to tfidf_vectorizer.pkl")

# Save Embedding Model (if available)
if USE_EMBEDDINGS and emb_model is not None:
    # For SentenceTransformer, it's often better to save the model itself via its save_pretrained method
    # or just its name and re-load it later if it's from Hugging Face Transformers.
    # If you want to pickle the object directly (might be large):
    with open('embedding_model.pkl', 'wb') as f:
        pickle.dump(emb_model, f)
    print("Embedding Model saved to embedding_model.pkl")
    # Alternatively, save its name and reload:
    # with open('embedding_model_name.txt', 'w') as f:
    #     f.write(embed_model_name)
    # print(f"Embedding Model name '{embed_model_name}' saved to embedding_model_name.txt")

# Save Reranker (if available)
if USE_RERANKER and 'reranker' in locals() and reranker is not None:
    with open('reranker_model.pkl', 'wb') as f:
        pickle.dump(reranker, f)
    print("Reranker Model saved to reranker_model.pkl")

# To 'save' the hybrid model, save its core components:
# 1. The TF-IDF vectorizer (already done)
# 2. The professor profiles dataframe (used for KG topics and profile text for reranking)
with open('prof_df.pkl', 'wb') as f:
    pickle.dump(prof_df, f)
print("Professor profiles DataFrame saved to prof_df.pkl")

"""
## Perhaps

- **Embeddings**: turn on `USE_EMBEDDINGS=True` and choose a model. Try `intfloat/multilingual-e5-large` for Thai/English.
- **Reranker**: set `USE_RERANKER=True` and use a cross-encoder (e.g., `BAAI/bge-reranker-large`) for better ordering.
- **Hybrid Weights**: adjust `w_tfidf` and `w_kg` in `hybrid_search`.
- **Topics Ontology**: normalize topic strings to an ontology (ACM/CSO/MeSH) for stronger KG overlap.
- **Capacity/Fairness**: add constraints in the final ranking to avoid overloading the same professors.
- **Cohort Matching**: add bipartite matching (Hungarian/ILP) as an optional cohort assignment step.
"""

